// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkTrac.Data;

#nullable disable

namespace WorkTrac.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20231115023001_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WorkTrac.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://robohash.org/velestvoluptatem.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "pivanusyev0@admin.ch",
                            FirstName = "Pooh",
                            LastName = "Ivanusyev"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://robohash.org/sitsitnulla.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "ptrump1@examiner.com",
                            FirstName = "Parke",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://robohash.org/rationequoarchitecto.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "agyppes2@cyberchimps.com",
                            FirstName = "Alvina",
                            LastName = "Gyppes"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://robohash.org/blanditiisfugiatipsam.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "evasyutin3@tamu.edu",
                            FirstName = "Ellissa",
                            LastName = "Vasyutin"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "https://robohash.org/aliquidsuntinventore.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "cdavy4@chicagotribune.com",
                            FirstName = "Cordelia",
                            LastName = "Davy"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "https://robohash.org/illoinciduntatque.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "aglide5@furl.net",
                            FirstName = "Aristotle",
                            LastName = "Glide"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "https://robohash.org/odioquinemo.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "earran6@rambler.ru",
                            FirstName = "Elisabetta",
                            LastName = "Arran"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "https://robohash.org/utautmolestiae.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "lbuncom7@xing.com",
                            FirstName = "Lesley",
                            LastName = "Buncom"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "https://robohash.org/debitisetcorporis.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "tcaselick8@amazon.com",
                            FirstName = "Tedd",
                            LastName = "Caselick"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "https://robohash.org/utminimafugit.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "ocoggles9@time.com",
                            FirstName = "Orella",
                            LastName = "Coggles"
                        },
                        new
                        {
                            Id = 11,
                            Avatar = "https://robohash.org/estautmagnam.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "zmalliona@paypal.com",
                            FirstName = "Zabrina",
                            LastName = "Mallion"
                        },
                        new
                        {
                            Id = 12,
                            Avatar = "https://robohash.org/voluptatessolutaipsa.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "kdarreeb@yellowpages.com",
                            FirstName = "Kate",
                            LastName = "Darree"
                        },
                        new
                        {
                            Id = 13,
                            Avatar = "https://robohash.org/quiullamblanditiis.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "rdanilovichc@forbes.com",
                            FirstName = "Ringo",
                            LastName = "Danilovich"
                        },
                        new
                        {
                            Id = 14,
                            Avatar = "https://robohash.org/autaenim.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "imcsporrind@pagesperso-orange.fr",
                            FirstName = "Ina",
                            LastName = "McSporrin"
                        },
                        new
                        {
                            Id = 15,
                            Avatar = "https://robohash.org/corruptiquidemconsectetur.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "egulleforde@zimbio.com",
                            FirstName = "Ellsworth",
                            LastName = "Gulleford"
                        },
                        new
                        {
                            Id = 16,
                            Avatar = "https://robohash.org/voluptasullamdebitis.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "srivelf@google.com.hk",
                            FirstName = "Say",
                            LastName = "Rivel"
                        },
                        new
                        {
                            Id = 17,
                            Avatar = "https://robohash.org/consequatursitmollitia.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "snowlandg@ask.com",
                            FirstName = "Samuel",
                            LastName = "Nowland"
                        },
                        new
                        {
                            Id = 18,
                            Avatar = "https://robohash.org/architectonesciuntmagni.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "kmartignonh@dmoz.org",
                            FirstName = "Katya",
                            LastName = "Martignon"
                        },
                        new
                        {
                            Id = 19,
                            Avatar = "https://robohash.org/velsedmolestiae.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "llenormandi@wiley.com",
                            FirstName = "Leshia",
                            LastName = "Lenormand"
                        },
                        new
                        {
                            Id = 20,
                            Avatar = "https://robohash.org/perspiciatissuntdolorum.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "uwelshj@mapquest.com",
                            FirstName = "Ursuline",
                            LastName = "Welsh"
                        },
                        new
                        {
                            Id = 21,
                            Avatar = "https://robohash.org/doloreducimusin.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "ochaucerk@cafepress.com",
                            FirstName = "Olympia",
                            LastName = "Chaucer"
                        },
                        new
                        {
                            Id = 22,
                            Avatar = "https://robohash.org/quiipsalaboriosam.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "kbillingsleyl@free.fr",
                            FirstName = "Kerri",
                            LastName = "Billingsley"
                        },
                        new
                        {
                            Id = 23,
                            Avatar = "https://robohash.org/repudiandaeetnostrum.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "byaldrenm@census.gov",
                            FirstName = "Brand",
                            LastName = "Yaldren"
                        },
                        new
                        {
                            Id = 24,
                            Avatar = "https://robohash.org/nonsitest.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "mbletchern@unesco.org",
                            FirstName = "Munroe",
                            LastName = "Bletcher"
                        },
                        new
                        {
                            Id = 25,
                            Avatar = "https://robohash.org/accusamusveniameligendi.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "mbetjeso@yellowpages.com",
                            FirstName = "Moina",
                            LastName = "Betjes"
                        },
                        new
                        {
                            Id = 26,
                            Avatar = "https://robohash.org/possimusvoluptatemodit.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "ryukhnevichp@moonfruit.com",
                            FirstName = "Riva",
                            LastName = "Yukhnevich"
                        },
                        new
                        {
                            Id = 27,
                            Avatar = "https://robohash.org/quoquianon.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "amcateerq@usgs.gov",
                            FirstName = "Alard",
                            LastName = "McAteer"
                        },
                        new
                        {
                            Id = 28,
                            Avatar = "https://robohash.org/quodenimnisi.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "smaddinr@wired.com",
                            FirstName = "Sadella",
                            LastName = "Maddin"
                        },
                        new
                        {
                            Id = 29,
                            Avatar = "https://robohash.org/sintveritatisminus.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "sbrusles@senate.gov",
                            FirstName = "Steven",
                            LastName = "Brusle"
                        },
                        new
                        {
                            Id = 30,
                            Avatar = "https://robohash.org/accusamusvoluptasillo.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "aleishmant@yellowbook.com",
                            FirstName = "Arv",
                            LastName = "Leishman"
                        },
                        new
                        {
                            Id = 31,
                            Avatar = "https://robohash.org/eligendinonquia.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "rplaschkeu@4shared.com",
                            FirstName = "Reinaldo",
                            LastName = "Plaschke"
                        },
                        new
                        {
                            Id = 32,
                            Avatar = "https://robohash.org/atquealiasdoloremque.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "istillyv@sbwire.com",
                            FirstName = "Iorgos",
                            LastName = "Stilly"
                        },
                        new
                        {
                            Id = 33,
                            Avatar = "https://robohash.org/illumofficianam.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "tricciardiellow@bbc.co.uk",
                            FirstName = "Terrell",
                            LastName = "Ricciardiello"
                        },
                        new
                        {
                            Id = 34,
                            Avatar = "https://robohash.org/sitetlabore.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "scasillisx@oaic.gov.au",
                            FirstName = "Sybille",
                            LastName = "Casillis"
                        },
                        new
                        {
                            Id = 35,
                            Avatar = "https://robohash.org/nullavelitconsequatur.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "jgooddingy@dropbox.com",
                            FirstName = "Jobye",
                            LastName = "Goodding"
                        },
                        new
                        {
                            Id = 36,
                            Avatar = "https://robohash.org/maximeutimpedit.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "cwinfieldz@ted.com",
                            FirstName = "Cleve",
                            LastName = "Winfield"
                        },
                        new
                        {
                            Id = 37,
                            Avatar = "https://robohash.org/eosetmolestiae.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "edotson10@alibaba.com",
                            FirstName = "Ernst",
                            LastName = "Dotson"
                        },
                        new
                        {
                            Id = 38,
                            Avatar = "https://robohash.org/verocumqueest.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "dvansalzberger11@php.net",
                            FirstName = "Denny",
                            LastName = "Van Salzberger"
                        },
                        new
                        {
                            Id = 39,
                            Avatar = "https://robohash.org/iureaveritatis.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "bpetru12@merriam-webster.com",
                            FirstName = "Benn",
                            LastName = "Petru"
                        },
                        new
                        {
                            Id = 40,
                            Avatar = "https://robohash.org/quidemmolestiaelaborum.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "hdreigher13@businessweek.com",
                            FirstName = "Helen",
                            LastName = "Dreigher"
                        },
                        new
                        {
                            Id = 41,
                            Avatar = "https://robohash.org/etperferendisquis.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "caubrey14@businesswire.com",
                            FirstName = "Cosimo",
                            LastName = "Aubrey"
                        },
                        new
                        {
                            Id = 42,
                            Avatar = "https://robohash.org/temporibuseaid.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "barran15@unblog.fr",
                            FirstName = "Barry",
                            LastName = "Arran"
                        },
                        new
                        {
                            Id = 43,
                            Avatar = "https://robohash.org/quisitomnis.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "shatchette16@cbsnews.com",
                            FirstName = "Sabra",
                            LastName = "Hatchette"
                        },
                        new
                        {
                            Id = 44,
                            Avatar = "https://robohash.org/errordoloremquetempora.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "vsabathe17@prnewswire.com",
                            FirstName = "Vinnie",
                            LastName = "Sabathe"
                        },
                        new
                        {
                            Id = 45,
                            Avatar = "https://robohash.org/sintevenietvel.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "tgranleese18@wufoo.com",
                            FirstName = "Townsend",
                            LastName = "Granleese"
                        },
                        new
                        {
                            Id = 46,
                            Avatar = "https://robohash.org/solutaidsunt.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "aislip19@abc.net.au",
                            FirstName = "Aila",
                            LastName = "Islip"
                        },
                        new
                        {
                            Id = 47,
                            Avatar = "https://robohash.org/magnamassumendaautem.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "dferryn1a@mashable.com",
                            FirstName = "Dierdre",
                            LastName = "Ferryn"
                        },
                        new
                        {
                            Id = 48,
                            Avatar = "https://robohash.org/eumquisporro.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "sblackmoor1b@joomla.org",
                            FirstName = "Sharyl",
                            LastName = "Blackmoor"
                        },
                        new
                        {
                            Id = 49,
                            Avatar = "https://robohash.org/sapienteipsaconsequatur.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "lmeriel1c@soundcloud.com",
                            FirstName = "Lisetta",
                            LastName = "Meriel"
                        },
                        new
                        {
                            Id = 50,
                            Avatar = "https://robohash.org/utsuntqui.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "seble1d@slashdot.org",
                            FirstName = "Shelby",
                            LastName = "Eble"
                        },
                        new
                        {
                            Id = 51,
                            Avatar = "https://robohash.org/suscipitquamquo.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "snisen1e@github.io",
                            FirstName = "Shela",
                            LastName = "Nisen"
                        },
                        new
                        {
                            Id = 52,
                            Avatar = "https://robohash.org/consecteturquiexpedita.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "cnelius1f@cnet.com",
                            FirstName = "Cristi",
                            LastName = "Nelius"
                        },
                        new
                        {
                            Id = 53,
                            Avatar = "https://robohash.org/accusamusautemlaborum.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "ldavidowich1g@walmart.com",
                            FirstName = "Leticia",
                            LastName = "Davidowich"
                        },
                        new
                        {
                            Id = 54,
                            Avatar = "https://robohash.org/quidemsuntmaiores.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "jionnidis1h@cnbc.com",
                            FirstName = "Joete",
                            LastName = "Ionnidis"
                        },
                        new
                        {
                            Id = 55,
                            Avatar = "https://robohash.org/enimestaut.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "ggayle1i@issuu.com",
                            FirstName = "Georgeta",
                            LastName = "Gayle"
                        },
                        new
                        {
                            Id = 56,
                            Avatar = "https://robohash.org/omnisetdistinctio.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "npercy1j@fotki.com",
                            FirstName = "Nicolais",
                            LastName = "Percy"
                        },
                        new
                        {
                            Id = 57,
                            Avatar = "https://robohash.org/nihilvoluptatumab.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "jloughton1k@digg.com",
                            FirstName = "Joellyn",
                            LastName = "Loughton"
                        },
                        new
                        {
                            Id = 58,
                            Avatar = "https://robohash.org/nequeabquidem.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "dbretton1l@omniture.com",
                            FirstName = "Davie",
                            LastName = "Bretton"
                        },
                        new
                        {
                            Id = 59,
                            Avatar = "https://robohash.org/autaliasquo.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "sdabbotdoyle1m@arstechnica.com",
                            FirstName = "Saree",
                            LastName = "D'Abbot-Doyle"
                        },
                        new
                        {
                            Id = 60,
                            Avatar = "https://robohash.org/etveniameum.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "hgloves1n@sun.com",
                            FirstName = "Hobie",
                            LastName = "Gloves"
                        },
                        new
                        {
                            Id = 61,
                            Avatar = "https://robohash.org/itaqueenimtemporibus.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "vweerdenburg1o@arstechnica.com",
                            FirstName = "Vanessa",
                            LastName = "Weerdenburg"
                        },
                        new
                        {
                            Id = 62,
                            Avatar = "https://robohash.org/veniamautautem.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "gledwitch1p@twitter.com",
                            FirstName = "Grove",
                            LastName = "Ledwitch"
                        },
                        new
                        {
                            Id = 63,
                            Avatar = "https://robohash.org/quiofficiaunde.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "gpoe1q@cafepress.com",
                            FirstName = "Gary",
                            LastName = "Poe"
                        },
                        new
                        {
                            Id = 64,
                            Avatar = "https://robohash.org/officiisnullavel.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "ydussy1r@home.pl",
                            FirstName = "Yolane",
                            LastName = "Dussy"
                        },
                        new
                        {
                            Id = 65,
                            Avatar = "https://robohash.org/estaliquidmagnam.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "mmcentegart1s@spiegel.de",
                            FirstName = "Mirna",
                            LastName = "McEntegart"
                        },
                        new
                        {
                            Id = 66,
                            Avatar = "https://robohash.org/voluptassuscipitut.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "spickless1t@merriam-webster.com",
                            FirstName = "Sarene",
                            LastName = "Pickless"
                        },
                        new
                        {
                            Id = 67,
                            Avatar = "https://robohash.org/quisrepudiandaenisi.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "amatyugin1u@phpbb.com",
                            FirstName = "Ashley",
                            LastName = "Matyugin"
                        },
                        new
                        {
                            Id = 68,
                            Avatar = "https://robohash.org/utitaqueenim.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "umintoft1v@joomla.org",
                            FirstName = "Ursa",
                            LastName = "Mintoft"
                        },
                        new
                        {
                            Id = 69,
                            Avatar = "https://robohash.org/isteetautem.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "vrockcliff1w@umn.edu",
                            FirstName = "Valera",
                            LastName = "Rockcliff"
                        },
                        new
                        {
                            Id = 70,
                            Avatar = "https://robohash.org/inquiomnis.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "bbohea1x@liveinternet.ru",
                            FirstName = "Brad",
                            LastName = "Bohea"
                        },
                        new
                        {
                            Id = 71,
                            Avatar = "https://robohash.org/aspernaturveroea.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "smathissen1y@soup.io",
                            FirstName = "Star",
                            LastName = "Mathissen"
                        },
                        new
                        {
                            Id = 72,
                            Avatar = "https://robohash.org/optiodelenitisoluta.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "hyoud1z@berkeley.edu",
                            FirstName = "Heather",
                            LastName = "Youd"
                        },
                        new
                        {
                            Id = 73,
                            Avatar = "https://robohash.org/rerumvoluptasminima.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "mcraythorne20@paginegialle.it",
                            FirstName = "Meredith",
                            LastName = "Craythorne"
                        },
                        new
                        {
                            Id = 74,
                            Avatar = "https://robohash.org/corruptivoluptatemrepudiandae.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "akenion21@360.cn",
                            FirstName = "Austin",
                            LastName = "Kenion"
                        },
                        new
                        {
                            Id = 75,
                            Avatar = "https://robohash.org/corporisearumdolor.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "cbradneck22@psu.edu",
                            FirstName = "Cosette",
                            LastName = "Bradneck"
                        },
                        new
                        {
                            Id = 76,
                            Avatar = "https://robohash.org/distinctiofugiataliquid.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "ttrimble23@miitbeian.gov.cn",
                            FirstName = "Terra",
                            LastName = "Trimble"
                        },
                        new
                        {
                            Id = 77,
                            Avatar = "https://robohash.org/idveritatisvel.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "rcaras24@ow.ly",
                            FirstName = "Roseanna",
                            LastName = "Caras"
                        },
                        new
                        {
                            Id = 78,
                            Avatar = "https://robohash.org/nihilrepellatprovident.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "jmichelle25@soup.io",
                            FirstName = "Johna",
                            LastName = "Michelle"
                        },
                        new
                        {
                            Id = 79,
                            Avatar = "https://robohash.org/aliquamiustooccaecati.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "hlindholm26@ft.com",
                            FirstName = "Harland",
                            LastName = "Lindholm"
                        },
                        new
                        {
                            Id = 80,
                            Avatar = "https://robohash.org/iustoetlibero.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "aconcannon27@xinhuanet.com",
                            FirstName = "Allayne",
                            LastName = "Concannon"
                        },
                        new
                        {
                            Id = 81,
                            Avatar = "https://robohash.org/eumomnisdolor.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "ldoerr28@marketwatch.com",
                            FirstName = "Lenna",
                            LastName = "Doerr"
                        },
                        new
                        {
                            Id = 82,
                            Avatar = "https://robohash.org/abquosea.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "ejenckes29@skype.com",
                            FirstName = "Edan",
                            LastName = "Jenckes"
                        },
                        new
                        {
                            Id = 83,
                            Avatar = "https://robohash.org/estadipisciquos.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "lpaffett2a@toplist.cz",
                            FirstName = "Luciano",
                            LastName = "Paffett"
                        },
                        new
                        {
                            Id = 84,
                            Avatar = "https://robohash.org/idplaceatnumquam.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "hgatteridge2b@geocities.com",
                            FirstName = "Hazlett",
                            LastName = "Gatteridge"
                        },
                        new
                        {
                            Id = 85,
                            Avatar = "https://robohash.org/autemestet.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "mlauga2c@cocolog-nifty.com",
                            FirstName = "Merrili",
                            LastName = "Lauga"
                        },
                        new
                        {
                            Id = 86,
                            Avatar = "https://robohash.org/etvoluptatumillo.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "kbeeho2d@github.com",
                            FirstName = "Kris",
                            LastName = "Beeho"
                        },
                        new
                        {
                            Id = 87,
                            Avatar = "https://robohash.org/temporibusnatuset.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "cpetrescu2e@nps.gov",
                            FirstName = "Carolyne",
                            LastName = "Petrescu"
                        },
                        new
                        {
                            Id = 88,
                            Avatar = "https://robohash.org/autemquiavoluptas.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "eberget2f@163.com",
                            FirstName = "Edith",
                            LastName = "Berget"
                        },
                        new
                        {
                            Id = 89,
                            Avatar = "https://robohash.org/namlaboremaiores.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "amaughan2g@youtu.be",
                            FirstName = "Agna",
                            LastName = "Maughan"
                        },
                        new
                        {
                            Id = 90,
                            Avatar = "https://robohash.org/ullamatmagni.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "ddarrigrand2h@youku.com",
                            FirstName = "Denise",
                            LastName = "Darrigrand"
                        },
                        new
                        {
                            Id = 91,
                            Avatar = "https://robohash.org/doloremetsed.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "cbuttler2i@aol.com",
                            FirstName = "Carly",
                            LastName = "Buttler"
                        },
                        new
                        {
                            Id = 92,
                            Avatar = "https://robohash.org/velofficiismaiores.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "fmciver2j@berkeley.edu",
                            FirstName = "Free",
                            LastName = "McIver"
                        },
                        new
                        {
                            Id = 93,
                            Avatar = "https://robohash.org/impeditetvoluptatibus.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "opetroulis2k@engadget.com",
                            FirstName = "Osbourn",
                            LastName = "Petroulis"
                        },
                        new
                        {
                            Id = 94,
                            Avatar = "https://robohash.org/facilisconsequaturnumquam.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "bthain2l@yellowpages.com",
                            FirstName = "Blaire",
                            LastName = "Thain"
                        },
                        new
                        {
                            Id = 95,
                            Avatar = "https://robohash.org/officiissuntconsequatur.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "rboxhall2m@meetup.com",
                            FirstName = "Raymund",
                            LastName = "Boxhall"
                        },
                        new
                        {
                            Id = 96,
                            Avatar = "https://robohash.org/facilisvelitquo.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "tesslemont2n@umn.edu",
                            FirstName = "Tod",
                            LastName = "Esslemont"
                        },
                        new
                        {
                            Id = 97,
                            Avatar = "https://robohash.org/itaquesitut.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "foppery2o@zdnet.com",
                            FirstName = "Florie",
                            LastName = "Oppery"
                        },
                        new
                        {
                            Id = 98,
                            Avatar = "https://robohash.org/nisiautitaque.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "pworrell2p@forbes.com",
                            FirstName = "Patrice",
                            LastName = "Worrell"
                        },
                        new
                        {
                            Id = 99,
                            Avatar = "https://robohash.org/aetsequi.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "morth2q@psu.edu",
                            FirstName = "Mikaela",
                            LastName = "Orth"
                        },
                        new
                        {
                            Id = 100,
                            Avatar = "https://robohash.org/dolorescumqueet.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "jdenney2r@hibu.com",
                            FirstName = "Joane",
                            LastName = "Denney"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
